<?php

return [
    'accounts' => [
        'title' => 'Accounts',
        'pk' => 'Account_ID',
        'procedures' => ['list' => 'sp_accounts_list', 'get' => 'sp_accounts_get', 'save' => 'sp_accounts_save', 'delete' => 'sp_accounts_delete'],
        'fields' => [
            ['name' => 'Account_Name', 'label' => 'Account Name', 'type' => 'text', 'required' => true],
            ['name' => 'Current_Balance', 'label' => 'Current Balance', 'type' => 'number', 'step' => '0.01'],
        ],
    ],
    'account_transfers' => [
        'title' => 'Account Transfers',
        'pk' => 'Transfer_ID',
        'procedures' => ['list' => 'sp_account_transfers_list', 'get' => 'sp_account_transfers_get', 'save' => 'sp_account_transfers_save', 'delete' => 'sp_account_transfers_delete'],
        'fields' => [
            ['name' => 'From_Account_ID', 'label' => 'From Account', 'type' => 'select', 'lookup' => ['procedure' => 'sp_accounts_list', 'value' => 'Account_ID', 'label' => 'Account_Name']],
            ['name' => 'To_Account_ID', 'label' => 'To Account', 'type' => 'select', 'lookup' => ['procedure' => 'sp_accounts_list', 'value' => 'Account_ID', 'label' => 'Account_Name']],
            ['name' => 'Amount', 'label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ['name' => 'Transfer_Date', 'label' => 'Transfer Date', 'type' => 'datetime-local'],
            ['name' => 'User_ID', 'label' => 'Created By', 'current_user' => true],
        ],
    ],
    'appointments' => [
        'title' => 'Appointments',
        'pk' => 'Appointment_ID',
        'procedures' => ['list' => 'sp_appointments_list', 'get' => 'sp_appointments_get', 'save' => 'sp_appointments_save', 'delete' => 'sp_appointments_delete'],
        'fields' => [
            ['name' => 'Patient_ID', 'label' => 'Patient', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Doctor_ID', 'label' => 'Doctor', 'type' => 'select', 'lookup' => ['procedure' => 'sp_doctors_list', 'value' => 'Doctor_ID', 'label' => 'Full_Name']],
            ['name' => 'Appointment_Date', 'label' => 'Appointment Date', 'type' => 'datetime-local', 'required' => true],
            ['name' => 'Status', 'label' => 'Status', 'type' => 'select', 'required' => true, 'options' => ['Pending', 'Completed', 'Cancelled']],
        ],
    ],
    'doctors' => [
        'title' => 'Doctors',
        'pk' => 'Doctor_ID',
        'procedures' => ['list' => 'sp_doctors_list', 'get' => 'sp_doctors_get', 'save' => 'sp_doctors_save', 'delete' => 'sp_doctors_delete'],
        'fields' => [
            ['name' => 'Full_Name', 'label' => 'Full Name', 'type' => 'text', 'required' => true],
            ['name' => 'Specialization', 'label' => 'Specialization', 'type' => 'text'],
            ['name' => 'Consultation_Fee', 'label' => 'Consultation Fee', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'User_ID', 'label' => 'Login account', 'type' => 'select', 'lookup' => ['procedure' => 'sp_users_list', 'value' => 'User_ID', 'label' => 'Username'], 'hint' => 'Hal username hal dhakhtar keliya ayuu ku xirmi karaa. Ka tag `-- Select --` haddii login loo baahnayn.'],
        ],
    ],
    'lab_results' => [
        'title' => 'Lab Results',
        'pk' => 'Result_ID',
        'procedures' => ['list' => 'sp_lab_results_list', 'get' => 'sp_lab_results_get', 'save' => 'sp_lab_results_save', 'delete' => 'sp_lab_results_delete'],
        'fields' => [
            ['name' => 'Visit_ID', 'label' => 'Visit', 'type' => 'select', 'lookup' => ['procedure' => 'sp_visits_list', 'value' => 'Visit_ID', 'label' => 'Patient_Name']],
            ['name' => 'Test_ID', 'label' => 'Lab Test', 'type' => 'select', 'lookup' => ['procedure' => 'sp_lab_tests_list', 'value' => 'Test_ID', 'label' => 'Test_Name']],
            ['name' => 'Result_Details', 'label' => 'Result Details', 'type' => 'textarea'],
            ['name' => 'Status', 'label' => 'Status', 'type' => 'select', 'options' => ['Pending', 'Completed']],
        ],
    ],
    'lab_tests' => [
        'title' => 'Lab Tests',
        'pk' => 'Test_ID',
        'procedures' => ['list' => 'sp_lab_tests_list', 'get' => 'sp_lab_tests_get', 'save' => 'sp_lab_tests_save', 'delete' => 'sp_lab_tests_delete'],
        'fields' => [
            ['name' => 'Test_Name', 'label' => 'Test Name', 'type' => 'text', 'required' => true],
            ['name' => 'Price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01', 'required' => true],
        ],
    ],
    'medicines' => [
        'title' => 'Medicines',
        'pk' => 'Medicine_ID',
        'procedures' => ['list' => 'sp_medicines_list', 'get' => 'sp_medicines_get', 'save' => 'sp_medicines_save', 'delete' => 'sp_medicines_delete'],
        'fields' => [
            ['name' => 'Medicine_Name', 'label' => 'Medicine Name', 'type' => 'text', 'required' => true],
            ['name' => 'Price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ['name' => 'Stock_Quantity', 'label' => 'Stock Quantity', 'type' => 'number', 'step' => '1', 'required' => true],
            ['name' => 'Expiry_Date', 'label' => 'Expiry Date', 'type' => 'date'],
        ],
    ],
    'menues' => [
        'title' => 'Menus',
        'pk' => 'menu_id',
        'procedures' => ['list' => 'sp_menues_list', 'get' => 'sp_menues_get', 'save' => 'sp_menues_save', 'delete' => 'sp_menues_delete'],
        'fields' => [
            ['name' => 'menu_name', 'label' => 'Menu Name', 'type' => 'text', 'required' => true],
            ['name' => 'icon', 'label' => 'Icon', 'type' => 'text'],
            ['name' => 'menu_group', 'label' => 'Menu Group', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'inactive']],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'step' => '1'],
        ],
    ],
    'nursing_records' => [
        'title' => 'Nursing Records',
        'pk' => 'Record_ID',
        'procedures' => ['list' => 'sp_nursing_records_list', 'get' => 'sp_nursing_records_get', 'save' => 'sp_nursing_records_save', 'delete' => 'sp_nursing_records_delete'],
        'fields' => [
            ['name' => 'Visit_ID', 'label' => 'Visit', 'type' => 'select', 'lookup' => ['procedure' => 'sp_visits_list', 'value' => 'Visit_ID', 'label' => 'Patient_Name']],
            ['name' => 'Service_ID', 'label' => 'Service', 'type' => 'select', 'lookup' => ['procedure' => 'sp_nursing_services_list', 'value' => 'Service_ID', 'label' => 'Service_Name']],
            ['name' => 'Medicine_Used', 'label' => 'Medicine Used', 'type' => 'text'],
            ['name' => 'Administered_By', 'label' => 'Administered By', 'current_user' => true],
            ['name' => 'Record_Date', 'label' => 'Record Date', 'type' => 'datetime-local'],
        ],
    ],
    'nursing_services' => [
        'title' => 'Nursing Services',
        'pk' => 'Service_ID',
        'procedures' => ['list' => 'sp_nursing_services_list', 'get' => 'sp_nursing_services_get', 'save' => 'sp_nursing_services_save', 'delete' => 'sp_nursing_services_delete'],
        'fields' => [
            ['name' => 'Service_Name', 'label' => 'Service Name', 'type' => 'text', 'required' => true],
            ['name' => 'Price', 'label' => 'Price', 'type' => 'number', 'step' => '0.01', 'required' => true],
        ],
    ],
    'patients' => [
        'title' => 'Patients',
        'pk' => 'Patient_ID',
        'procedures' => ['list' => 'sp_patients_list', 'get' => 'sp_patients_get', 'save' => 'sp_patients_save', 'delete' => 'sp_patients_delete'],
        'fields' => [
            ['name' => 'Full_Name', 'label' => 'Full Name', 'type' => 'text', 'required' => true],
            ['name' => 'Phone_Number', 'label' => 'Phone Number', 'type' => 'tel'],
            ['name' => 'Sex', 'label' => 'Sex', 'type' => 'select', 'options' => ['Male', 'Female']],
            ['name' => 'Age_Group', 'label' => 'Age Group', 'type' => 'select', 'options' => ['Child', 'Adult']],
            ['name' => 'Patient_Type', 'label' => 'Patient Type', 'type' => 'select', 'options' => ['Bille', 'Maalinle']],
            ['name' => 'Guarantor_ID', 'label' => 'Guarantor', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Relationship', 'label' => 'Relationship', 'type' => 'select', 'options' => ['Self', 'Child', 'Spouse', 'Other']],
            ['name' => 'Credit_Limit', 'label' => 'Credit Limit', 'type' => 'number', 'step' => '0.01'],
            ['name' => 'Current_Balance', 'label' => 'Current Balance', 'type' => 'number', 'step' => '0.01'],
        ],
    ],
    'payments' => [
        'title' => 'Payments',
        'pk' => 'Payment_ID',
        'procedures' => ['list' => 'sp_payments_list', 'get' => 'sp_payments_get', 'save' => 'sp_payments_save', 'delete' => 'sp_payments_delete'],
        'fields' => [
            ['name' => 'Patient_ID', 'label' => 'Patient', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Account_ID', 'label' => 'Account', 'type' => 'select', 'lookup' => ['procedure' => 'sp_accounts_list', 'value' => 'Account_ID', 'label' => 'Account_Name']],
            ['name' => 'Amount', 'label' => 'Amount', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ['name' => 'Payment_Method', 'label' => 'Payment Method', 'type' => 'select', 'options' => ['EVC Plus', 'eDahab', 'Cash', 'Bank'], 'required' => true],
            ['name' => 'Transaction_Ref', 'label' => 'Transaction Ref', 'type' => 'text'],
            ['name' => 'Payment_Date', 'label' => 'Payment Date', 'type' => 'datetime-local'],
            ['name' => 'User_ID', 'label' => 'Created By', 'current_user' => true],
        ],
    ],
    'pharmacy_sales' => [
        'title' => 'Pharmacy Sales',
        'pk' => 'Sale_ID',
        'procedures' => ['list' => 'sp_pharmacy_sales_list', 'get' => 'sp_pharmacy_sales_get', 'save' => 'sp_pharmacy_sales_save', 'delete' => 'sp_pharmacy_sales_delete'],
        'fields' => [
            ['name' => 'Patient_ID', 'label' => 'Patient', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Medicine_ID', 'label' => 'Medicine', 'type' => 'select', 'lookup' => ['procedure' => 'sp_medicines_list', 'value' => 'Medicine_ID', 'label' => 'Medicine_Name']],
            ['name' => 'Quantity', 'label' => 'Quantity', 'type' => 'number', 'step' => '1', 'required' => true],
            ['name' => 'Total_Price', 'label' => 'Total Price', 'type' => 'number', 'step' => '0.01', 'required' => true],
            ['name' => 'Sale_Date', 'label' => 'Sale Date', 'type' => 'datetime-local'],
            ['name' => 'User_ID', 'label' => 'Created By', 'current_user' => true],
        ],
    ],
    'prescriptions' => [
        'title' => 'Prescriptions',
        'pk' => 'Prescription_ID',
        'procedures' => ['list' => 'sp_prescriptions_list', 'get' => 'sp_prescriptions_get', 'save' => 'sp_prescriptions_save', 'delete' => 'sp_prescriptions_delete'],
        'fields' => [
            ['name' => 'Visit_ID', 'label' => 'Visit', 'type' => 'select', 'lookup' => ['procedure' => 'sp_visits_list', 'value' => 'Visit_ID', 'label' => 'Patient_Name']],
            ['name' => 'Medicine_ID', 'label' => 'Medicine', 'type' => 'select', 'lookup' => ['procedure' => 'sp_medicines_list', 'value' => 'Medicine_ID', 'label' => 'Medicine_Name']],
            ['name' => 'Dosage', 'label' => 'Dosage', 'type' => 'text'],
        ],
    ],
    'roles' => [
        'title' => 'Roles',
        'pk' => 'Role_ID',
        'procedures' => ['list' => 'sp_roles_list', 'get' => 'sp_roles_get', 'save' => 'sp_roles_save', 'delete' => 'sp_roles_delete'],
        'fields' => [
            ['name' => 'Role_Name', 'label' => 'Role Name', 'type' => 'text', 'required' => true],
        ],
    ],
    'sms_logs' => [
        'title' => 'SMS Logs',
        'pk' => 'Log_ID',
        'procedures' => ['list' => 'sp_sms_logs_list', 'get' => 'sp_sms_logs_get', 'save' => 'sp_sms_logs_save', 'delete' => 'sp_sms_logs_delete'],
        'fields' => [
            ['name' => 'Patient_ID', 'label' => 'Patient', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Message_Body', 'label' => 'Message Body', 'type' => 'textarea', 'required' => true],
            ['name' => 'Message_Type', 'label' => 'Message Type', 'type' => 'select', 'options' => ['Bill Reminder', 'Lab Result', 'General'], 'required' => true],
            ['name' => 'Sent_Date', 'label' => 'Sent Date', 'type' => 'datetime-local'],
        ],
    ],
    'staff' => [
        'title' => 'Staff directory',
        'pk' => 'Staff_ID',
        'procedures' => ['list' => 'sp_staff_list', 'get' => 'sp_staff_get', 'save' => 'sp_staff_save', 'delete' => 'sp_staff_delete'],
        'fields' => [
            ['name' => 'User_ID', 'label' => 'Login account', 'type' => 'select', 'lookup' => ['procedure' => 'sp_users_list', 'value' => 'User_ID', 'label' => 'Username'], 'required' => true, 'hint' => 'Dooro akoonka users (Doctor, Receptionist, Nurse, Lab Technician, Pharmacist, …). Hal user hal shaqaale keliya. Jagada waxaa lagu arkayaa Role ee akoonka.'],
            ['name' => 'Full_Name', 'label' => 'Full Name', 'type' => 'text', 'required' => true],
            ['name' => 'Phone_Number', 'label' => 'Phone', 'type' => 'tel'],
            ['name' => 'Credential_Or_Badge', 'label' => 'Credential / badge', 'type' => 'text', 'hint' => 'For non-doctors: license, staff ID, pharmacy ID, etc.'],
            ['name' => 'Notes', 'label' => 'Notes', 'type' => 'textarea'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'inactive'], 'required' => true],
        ],
    ],
    'submenues' => [
        'title' => 'Submenus',
        'pk' => 'submenu_id',
        'procedures' => ['list' => 'sp_submenues_list', 'get' => 'sp_submenues_get', 'save' => 'sp_submenues_save', 'delete' => 'sp_submenues_delete'],
        'fields' => [
            ['name' => 'menu_id', 'label' => 'Parent Menu', 'type' => 'select', 'lookup' => ['procedure' => 'sp_menues_list', 'value' => 'menu_id', 'label' => 'menu_name'], 'required' => true],
            ['name' => 'submenu_name', 'label' => 'Submenu Name', 'type' => 'text', 'required' => true],
            ['name' => 'menu_url', 'label' => 'Menu URL', 'type' => 'text', 'required' => true],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'inactive']],
            ['name' => 'sort_order', 'label' => 'Sort Order', 'type' => 'number', 'step' => '1'],
        ],
    ],
    'users' => [
        'title' => 'Users',
        'pk' => 'User_ID',
        'procedures' => ['list' => 'sp_users_list', 'get' => 'sp_users_get', 'save' => 'sp_users_save', 'delete' => 'sp_users_delete'],
        'fields' => [
            ['name' => 'Username', 'label' => 'Username', 'type' => 'text', 'required' => true],
            [
                'name' => 'Password_Hash',
                'label' => 'Password',
                'type' => 'password',
                'required' => false,
                'hint' => 'Required for new users. When editing, leave blank to keep the current password.',
            ],
            ['name' => 'Role_ID', 'label' => 'Role', 'type' => 'select', 'lookup' => ['procedure' => 'sp_roles_list', 'value' => 'Role_ID', 'label' => 'Role_Name']],
            ['name' => 'email', 'label' => 'Email', 'type' => 'email'],
            ['name' => 'image', 'label' => 'Image', 'type' => 'text'],
            ['name' => 'status', 'label' => 'Status', 'type' => 'select', 'options' => ['active', 'inactive']],
        ],
    ],
    'user_privileges' => [
        'title' => 'User Privileges',
        'pk' => 'privilege_id',
        'procedures' => ['list' => 'sp_user_privileges_list', 'get' => 'sp_user_privileges_get', 'save' => 'sp_user_privileges_save', 'delete' => 'sp_user_privileges_delete'],
        'fields' => [
            ['name' => 'User_ID', 'label' => 'User', 'type' => 'select', 'lookup' => ['procedure' => 'sp_users_list', 'value' => 'User_ID', 'label' => 'Username'], 'required' => true],
            ['name' => 'submenu_id', 'label' => 'Submenu', 'type' => 'select', 'lookup' => ['procedure' => 'sp_submenues_list', 'value' => 'submenu_id', 'label' => 'submenu_name'], 'required' => true],
            ['name' => 'submenu_name', 'label' => 'Submenu Name', 'type' => 'text', 'required' => true],
            ['name' => 'can_view', 'label' => 'Can View', 'type' => 'checkbox'],
            ['name' => 'can_insert', 'label' => 'Can Insert', 'type' => 'checkbox'],
            ['name' => 'can_update', 'label' => 'Can Update', 'type' => 'checkbox'],
            ['name' => 'can_delete', 'label' => 'Can Delete', 'type' => 'checkbox'],
        ],
    ],
    'visits' => [
        'title' => 'Visits',
        'pk' => 'Visit_ID',
        'procedures' => ['list' => 'sp_visits_list', 'get' => 'sp_visits_get', 'save' => 'sp_visits_save', 'delete' => 'sp_visits_delete'],
        'fields' => [
            ['name' => 'Patient_ID', 'label' => 'Patient', 'type' => 'select', 'lookup' => ['procedure' => 'sp_patients_list', 'value' => 'Patient_ID', 'label' => 'Full_Name']],
            ['name' => 'Doctor_ID', 'label' => 'Doctor', 'type' => 'select', 'lookup' => ['procedure' => 'sp_doctors_list', 'value' => 'Doctor_ID', 'label' => 'Full_Name']],
            ['name' => 'Visit_Date', 'label' => 'Visit Date', 'type' => 'datetime-local'],
            ['name' => 'Notes', 'label' => 'Notes', 'type' => 'textarea'],
        ],
    ],
];
